src/Entity/Photo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PhotoRepository")
 */
class Photo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $directory;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $uploader;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getDirectory(): ?string
    {
        return $this->directory;
    }

    public function setDirectory(?string $directory): self
    {
        $this->directory = $directory;

        return $this;
    }

    public function getUploader(): ?string
    {
        return $this->uploader;
    }

    public function setUploader(string $uploader): self
    {
        $this->uploader = $uploader;

        return $this;
    }

    public function getImagePath()
    {
        return $this->getFilename();
    }
}

src/Form/Photo/PhotoFormType.php
<?php

namespace App\Form\Photo;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Image;

class PhotoFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
      ->add('imageFile', FileType::class, [
        'mapped' => false,
        'constraints' => [
          new Image([
            'maxSize' => '5M',
          ]),
        ],
      ])
      ->add('directory', TextType::class, [
        'required' => false,
      ])
      ->add('uploader', TextType::class);
    }
}

src/Controller/Photo/PhotoController.php
<?php

namespace App\Controller\Photo;

use App\Entity\Photo;
use App\Form\Photo\PhotoFormType;
use App\Repository\PhotoRepository;
use App\Service\UploaderHelper;
use App\Template\Annotation\MenuItem;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/photo", name="photo_")
 */
class PhotoController extends AbstractController
{
    /**
     * @MenuItem(title="Foto's")
     * @Route("/", name="index", methods={"GET"})
     */
    public function indexAction(PhotoRepository $repo)
    {
        $photos = $repo->findAll();

        return $this->render('photo/overview.html.twig', [
      'images' => $photos,
    ]);
    }

    /**
     * @Route("/new", name="new")
     */
    public function new(EntityManagerInterface $em, Request $request, UploaderHelper $uploaderHelper)
    {
        $form = $this->createForm(PhotoFormType::class, new Photo());

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $photo = $form->getData();
            $uploadedFile = $form['imageFile']->getData();
            if ($uploadedFile) {
                $newFilename = $uploaderHelper->uploadImage($uploadedFile);
                $photo->setFilename($newFilename);
            }
            $em->persist($photo);
            $em->flush();

            $this->addFlash('success', 'The picture has been uploaded!');

            return $this->redirectToRoute('photo_index');
        }

        return $this->render('photo/new.html.twig', [
      'photoForm' => $form->createView(),
    ]);
    }

    /**
     * $Route("/edit, name="edit").
     */
    public function edit(EntityManagerInterface $em, Request $request, UploaderHelper $uploaderHelper)
    {
    }
}

templates/photo/_form.html.twig
{{ form_start(photoForm) }}


<div class="row">
	<div class="col-sm-9">
		{{ form_row(photoForm.imageFile) }}
	</div>
	<div class="col-sm-9">
		{% if photoForm.vars.data.filename %}
			<img src="{{ photoForm.imagePath | imagine_filter('thumbnail_small') }}">
		{% endif %}
	</div>
</div>
{{ form_row(photoForm.directory, {
    label: 'Prefered subdirectory'
}) }}
{{ form_row(photoForm.uploader, {
    label: 'Your name'
}) }}

<button type="submit" class="btn btn-primary">{{ button_text}}</button>
{{ form_end(photoForm) }}

templates/photo/new.html.twig
{% extends "layout.html.twig" %}
{% set page_title = 'Upload' %}

{% block body %}
	{{ include('photo/_form.html.twig', {
    button_text: 'Upload!' 
  }) }}
{% endblock %}

templates/photo/overview.html.twig
{% extends 'layout.html.twig' %}

{% set page_title = 'View all' %}

{% block body %}
	<a href="{{ path('photo_new') }}">Upload new image.</a>
	{% for image in images %}
		<div class="article-container my-1">
			<a href="{{ uploaded_asset(image.imagePath) }}" target="_blank">
				<img class="article-img" width="42" src="{{ image.imagePath | imagine_filter('thumbnail_small') }}">
			</a>
		</div>
	{% endfor %}
</div>{% endblock %}